### ISSUE TITLE
Access Denied for MAE-pretrained weights and Full MAE weights

### ISSUE THREAD

**Issue by Swetha5** [facebookresearch/maws#4]
Hello @mannatsingh!

I want to express my appreciation for the incredible work you have done with comprehensive comparisons. Thank you so much for open-sourcing your project and making the model weights available to the public!

- However, it appears that there is an issue with accessing the weights for the [MAE-pretrained models](https://dl.fbaipublicfiles.com/maws/pretrain/mae/vit_h14.pt). The links provided for weights are not accessible.

  > AccessDeniedAccess DeniedB8N6NH8TMN6HPXEVh9mtVVSOFGkkOBRNPHzcuER0Yh1dn1uV39z9vSzYkAvIkKw57Pmqu0aUwiU1HERnfwmLWWiy0IOwxN2Xe1qfNw==

  Can you please resolve the access issue for model weights ? Can you confirm if these MAE weights are pre-trained on IG-3B data ?

- The released weights for MAE models only contains encoder weights, where can I get the full model weights i.e., both MAE encoder and decoder ?

**Comment by mannatsingh** [comment]
@Swetha5 thank you so much for your kind words and glad to hear you find out wok useful :)

thanks for pointing out the issue, it should be resolved now after https://github.com/facebookresearch/maws/commit/2fd156d5a394c4726bfcd2559bf44fdd7d7a4a17 for B/16 and an internal fix for H/14. Please let me know if you still run into any issues!

Yes, these are pretrained on IG-3B. For the ViT-2B since there are no Imagenet pretrained weights we release those as well.

> The released weights for MAE models only contains encoder weights, where can I get the full model weights i.e., both MAE encoder and decoder ?

You are right, these are encoder only weights. Unfortunately we don't have approvals to release the decoder weights.

**Comment by Swetha5** [comment]
Thank you, @mannatsingh, for your prompt response and for resolving the issue!

> You are right, these are encoder only weights. Unfortunately we don't have approvals to release the decoder weights.

Regarding the MAE weights, is there a plan to release them in future ? I'm interested in the full MAE weights, is there a way to request the decoder weights ?

**Comment by mannatsingh** [comment]
@Swetha5 I'm afraid there are no plans to release the decoder weights unfortunately
